notifications:
  email: false
sudo: enabled
os: linux
language: python
cache: pip
python: 3.7-dev
env:
  global:
    - GH_REPO=Drakkar-Software/OctoBot-Websockets
    - DEPLOY_BRANCH=master
    - PACKAGE_FOLDER=octobot_websockets
    - secure: arlSx4F6rn1H8Do9+WoZlZ16SkimBrTmw39r4LXe4tHoJK/kiFphRcQlKR3FGa47OGohCBqEVFKPYgeZd7i4j6pL+LMwgkHEZI/B88DD8NGnuEHbu9FCWssDjhQylxQEeZ6uywTTAQI1yYp0vlme2jAnuvCutQoFvVSlOP5To3Dkztrh78OAS8GZDJ/W3C9WT3y333eaOScDUbhfNjbujc1ke55onld8k6FFxp1QT4bXs9XGHpxGb2U7AhTe2XFawJ3VnTP4SVhQtlkuon8BCuphAKFOJWtpI/56B2SB+QlHPZE3euztlkbQzqR3ZLgO/lL1LNkTJDpWnzufytZWIGRKCggCckliC1bQGtmjlK37cqqbycw4xgCLhrFcO8EkMxwy+GNMqOPDgQ7RcpKxmQRgUIHzzSgZllAJdSPXLrJCVdT5BcEsTWMgTWnSMHv5k1arWmGwSfzXlTgnRkhV2jUdhbTkZOHQVhqAe5Sem/UnSnNGsDFI5soiie0leTm/1N9Css6SBWh7SeZzT+QKcA+Tzm5iMc1IttN/FQx0G1H13Nx/FXOY0MYCkwb71AB+76yA+hy1bCQUiGX8GT4i+yBa27nk4grBzfpHBJIbNmq+/m1uzfevEGW2ikk+CjAu4juJVHzKEe/IZIUby6mRtiRuPgem7vkGs/ESTHtaWbA=
    - secure: VwaVY9msyZi1TwpPMZjc7aSK9ihqs9+GU6AEZEG5KzWwYvHodRu4iX/gg+50Fn4JSAw9zhvtzcS5V3S0ezFYfXpotqswQ5532Z0iywgB4G/eWgtEhQ7sMiyrFTcOTVI1SHpAvEwoQCSTVWZZ5xGQCTGveGWV9VqygF9huEbxpsQd1gGOQQDPpCYkmx8HNm/JIHq0KCYeVnYOTJf3dHDvzovuUSmIljUcdQtAJyKPSlGLeN/SMPhJ6Wuog9UGvS7/JSrQfyE1zjgWMuJdy9N4myeik22dNOH+Lzf4z/J2OX8EPKXBMiTu5X714bDv5tYjomyMEtk7kzk71PKFywZJovKrL+SBRa7lmfsGbA5ndhe8tULC2xLun5pQHSXawZqpY/SP1xFoXOzILaqWQq1dLZu4D2t032AoaZoxi6wsZA6dNr88iF0o0BsnHFFzAQYBtiMO859a4MiD7QS0s1+PhsBcW9X5QBeX59U6GDPGiWjzj5Zhiunq55jLMBA4lWAuu030EyUn5B6kzJ4nhLYAF04TPt8iwHYAjKfQTaH0v5PB7ZEwpzkxXotiwIy5N+NZqlq8Ok4TjOZqVxKrcLkhR87erkd+Ib37ZH7gmwjh8CuCkrtl45butfQ5U1DQsbY7GWANj61r3NbzpuTzU1l3v6/97NOdhIfbdgq4JuhY+fI=

install:
  - python3 -m pip install --prefer-binary -r dev_requirements.txt -r requirements.txt

matrix:
  include:
    - name: "Linux - Python 3.7-dev - Cython compilation"
      stage: build
      os: linux
      python: 3.7-dev
      language: python
      script:
        - python3 setup.py build_ext --inplace

    - name: "Linux - Python 3.7-dev - Python sources"
      stage: test
      os: linux
      python: 3.7-dev
      language: python
      script:
        - pytest --cov=. --cov-config=.coveragerc --durations=0 -rw tests
      after_success:
        - if [ $TRAVIS_PULL_REQUEST == "false" ]; then coveralls; fi

    - name: "Linux - Python 3.7-dev - Installed"
      stage: test
      os: linux
      python: 3.7-dev
      language: python
      script:
        - python3 setup.py install
        - rm -rf $PACKAGE_FOLDER
        - pytest tests

    - name: "Linux - Python 3 nightly - Deploy"
      stage: deploy
      script:
        - ls
      deploy:
        - provider: pypi
          user:
            secure: Sc5P4n7mhQC3VpynOYR+ni2tJFANv2a0kdRfhWm97YA5/ofUss7M9/35+pFmfcyK7cawhhrn+xLzaD7A5sxHTBD855LevakapWBQL8it8gW62MzG8YnCccf04FfDIKEBYtuLEuChN5Q91cMWgSWUvFhke3tQIEBMrMzbYxHTkWpsfV1KN6A7GXr1Ijc+cvM82JtPD5JfcrLGc7oI40+ELBOktOYXWT7+wZIE1uSUALaHXO0nJMUJjAQspHOGqQVePtq5o4a9faDxkrny6eiSMcq+rB1F6df1i3YaAXNim+StoLDJ1JABS12pfJ2frJjA3LxvaiKh3iJHJo2PGgjKMru3u06VM+B9all9rRPQWV4msDBpD5/GbQBjBKZQQJJ8tw0hnkXDVwTRsgsNlLb4VQNZYjsyw2zXrQdEofRgLCffhMFjf6vrZ1BwK8+f/6mNuPDGKsv3AUpNhA19CXRYvfw3wrQqRDNX3fBrHKxf2/Tbk8ZFSfPVziJlnTQCSNMF2K6s9TT0gkrK99bvGMqAlKmUvkH37BBht48+ZGtHEIXW0hRRDsDJEBnkL0ur+ABUwfqRierNz0xTr62rtiLBgdwAP/Pe8VMZrHWFYCBBlaKgVvSbgWdoEp91DkVop7Htn+zwG6pE82LHmTx9du9iWe6X60OJNjC4FRJumu3iibs=
          password:
            secure: GIqSprZpjJbI9xoVzpPOPJe75EUrsajvwKMnWY/+ihmQud0KiwYESIGLP96/Fj43juY2Gb8os2ASOxI9jmj5xpF8xxOoXE71te4hPAhX+9rAY7XMl67K+ow1E9P2cxa7Vbik6o07YLvzf6xWcUR6ThSckKDJVG7aRtfEJvQGKHCsvoiA0Vwe3GPG+lAIb/8ugIZ/4AY3Y9wpTsJVgjl51QISORJS+QQZBc5zezPWTy6dHFB/exmi8h4wQKZIp8586yswSCJyE0LO/SPniUNKYrAJ8RbroqfSMRNhOOMIaNof6vogrnlSBxLsYxToyODxr9BFm8g+8Ut0VtXtvTbFPyhgUpOjF6B03WZw8AhDnbfKZjfFhxv5WDQDmMqGy4LMxHgVDVU1lEJ1aoa2hdBRE4lOFHCEZfyEFq6IbogEZc1bn6FTbVSXk7CUM14RRK1KgIQ0+knN27ytyMhurr/EWYxr+Ez3xnHQl5xFQcXgF6V+juvjK6VizIEE3vDC6YYUKkuO2qrpiEYkKya1I2AGHPF549XKApOqRo/GgPcAPYo1gwyYfhXvd/iYo+FalK5TsdQKpZl3EKkIdJfk7PzpPAjRFRS1VvZsaxalPUSDMVueyVXffZSbtcBPdk3psvC6S924nTnOjVmHYMyvXuUDDMC8bzlsZgyMdrWLtRAer8E=
          skip_existing: true
          skip_cleanup: true
          distributions: "sdist"
          on:
            repo: $GH_REPO
            branch: $DEPLOY_BRANCH
            tags: true
            condition: $TRAVIS_OS_NAME = 'linux'
        - provider: script
          script: docker run -it -e PYPI_USERNAME=$PYPI_USERNAME -e PYPI_PASSWORD=$PYPI_PASSWORD -v $(pwd):/project drakkarsoftware/octobot-pypi-deploy:i686 "i686" "cp37-cp37m" "cp37"
          skip_cleanup: true
          on:
            repo: "$GH_REPO"
            branch: "$DEPLOY_BRANCH"
            tags: true
            condition: "$TRAVIS_OS_NAME = 'linux'"
        - provider: script
          script: docker run -it -e PYPI_USERNAME=$PYPI_USERNAME -e PYPI_PASSWORD=$PYPI_PASSWORD -v $(pwd):/project drakkarsoftware/octobot-pypi-deploy:x86_64 "x86_64" "cp37-cp37m" "cp37"
          skip_cleanup: true
          on:
            repo: "$GH_REPO"
            branch: "$DEPLOY_BRANCH"
            tags: true
            condition: "$TRAVIS_OS_NAME = 'linux'"

    - name: "OSX - Python 3.7 - Deploy"
      stage: deploy
      os: osx
      osx_image: xcode11    # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install: python3 --version ; pip3 --version ; sw_vers
      before_cache:
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          - "$HOME/Library/Caches/pip"
      script:
        - python3 setup.py build_ext --inplace
        - pytest tests
      deploy:
        - provider: script
          script: python3 setup.py bdist_wheel && python3 -m twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD --skip-existing
          skip_cleanup: true
          on:
            repo: "$GH_REPO"
            branch: "$DEPLOY_BRANCH"
            tags: true
            condition: "$TRAVIS_OS_NAME = 'osx'"
